---
- name: Create EC2 instance
  hosts: all
#  connection: local
  gather_facts: false
  vars:
    ec2_name: Lightspeed-instance
    ec2_region: us-east-1
    ec2_image: ami-016eb5d644c333ccb
    ec2_instance_type: t2.micro
    ec2_keypair: aac
    ec2_security_group: default
    ec2_vpc_subnet_id: "{{ vpc_subnet_id }}"
    ec2_assign_public_ip: true
    ec2_tag_env: develop
  tasks:
    - name: Get aws vpc subnet info
      register: vpc_subnet_info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ ec2_region }}"
#        filters:
#          vpc-id: "{{ ec2_vpc_id }}"

    - name: Create EC2 instance with public_ip_address using amazon.aws.ec2_instance module
      amazon.aws.ec2_instance:
        region: "{{ ec2_region }}"
        key_name: aac
        image: "{{ _image_ }}"
        instance_type: "{{ ec2_instance_type }}"
        vpc_subnet_id: "{{ vpc_subnet_info.subnets[0].id }}"
        security_group: "{{ ec2_security_group }}"
        network:
          assign_public_ip: true
        wait: true
        wait_timeout: 600
      register: ec2_instance


    - name: Output public_ip_address and private_ip_address
      ansible.builtin.debug:
        msg:
          - public_ip_address: "{{ ec2.instances[0].public_ip_address }}"
          - private_ip_address: "{{ ec2.instances[0].private_ip_address }}"

 