---
- name: EC2 Create Instance
  hosts: all
#  conection: local
  gather_facts: false

  module_defaults:
    group/aws:
      region: us-east-1

  vars:
    my_instance:
      name: instance-lightspeed-01
      image_id: ami-016eb5d644c333ccb # RHEL 9 us-east-1
      network:
        assign_public_ip: true
      subnet_id: subnet-04431049f14b80825 # VPC Subnet
      tags:
        function: demo-lightspeed
      security_group: default
      wait: true
    key_name: aac

  tasks:
    # Get subnet-lightspeed info & create vpc_subnet_id var
    # Content suggestion provided by Ansible Lightspeed
    - name: Get subnet-lightspeed info
      register: subnet_info
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          tag:Name: "{{ my_instance.subnet_id }}"

    - name: print all subnet_ids
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "{{ subnet_info.subnets | map(attribute='id') | list }}"
    
    - name: Create vpc_subnet_id var
      ansible.builtin.set_fact:
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
    
   
    - name: Create t3.small instance using my_instance var
      # Content suggestion provided by Ansible Lightspeed
      amazon.aws.ec2_instance:
        name: "{{ my_instance.name }}"
        image_id: "{{ my_instance.image_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: t3.small
        network: "{{ my_instance.network }}"
        key_name: "{{ key_name }}"
        tags: "{{ my_instance.tags }}"
        wait: "{{ my_instance.wait }}"
        wait_timeout: 600
        security_group: "{{ my_instance.security_group }}"
        subnet_id: "{{ my_instance.subnet_id }}"
      register: ec2_instance
    
    - name: Create var from public_ip_address with retry
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.set_fact:
        public_ip_address: "{{ ec2_instance.instances[0].public_ip_address }}"
      retries: 10
      delay: 10
      until: ec2_instance.instances[0].public_ip_address is defined
    
    - name: Print it out
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "{{ public_ip_address }}"