---
- name: EC2 Create Instance
  hosts: all
#  conection: local
  gather_facts: false

  module_defaults:
    group/aws:
      region: us-east-1

  vars:
    my_instance:
      name: instance-lightspeed-01
      key_name: aac
      image_id: ami-016eb5d644c333ccb # RHEL 9 us-east-1
      network:
        assign_public_ip: true
      subnet_id: subnet-04431049f14b80825 # VPC Subnet
#      tags:
#        function: demo-lightspeed
      security_group: default
      wait: true

  tasks:
    - name: Create t3.small instance using my_instance var
      # Content suggestion provided by Ansible Lightspeed
      amazon.aws.ec2_instance:
        instance_type: t3.small
        image_id: "{{ my_instance.image_id }}"
        key_name: "{{ _key_name_ }}"
        network: "{{ my_instance.network }}"
        security_group: "{{ my_instance.security_group }}"
        wait: "{{ my_instance.wait }}"
        user_data: |
        name: "{{ my_instance.name }}"
        subnet_id: "{{ my_instance.subnet_id }}"
    
    - name: Create var from public_ip_address with retry
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.set_fact:
        public_ip_address: "{{ public_ip_address }}"
      retries: 10
      delay: 10
      until: public_ip_address is defined
      amazon.aws.ec2_instance_info:
        filters:
          instance-state-name: running
          public-ip-address: "{{ public_ip_address }}"
        
    - name: Print it out
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.debug:
        msg: "{{ public_ip_address }}"
    
